"""empty message

Revision ID: 1983b9d36955
Revises: 0e37086e4138
Create Date: 2020-11-22 10:50:19.662263

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1983b9d36955'
down_revision = '0e37086e4138'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'users', 'tasks', ['task_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    # ### end Alembic commands ###
